(defun fatia(lista n m)
    (if (null lista)
        NIL
    )
    (if (= m n)
        ()
        (cons (enesimo lista n) (fatia lista (1+ n) m))
    )
)

(defun enesimo(lista n)
    (if (null lista)
        NIL
    )
    (if (= n 0)
        (car lista)
        (enesimo (cdr lista) (1- n))
    )
)

(defun main()
    (write-line (write-to-string (fatia '(1 2 3 4 5) 0 0)))
    (write-line (write-to-string (fatia '(1 2 3 4 5) 0 1)))
    (write-line (write-to-string (fatia '(1 2 3 4 5) 0 2)))
    (write-line (write-to-string (fatia '(1 2 3 4 5) 0 3)))
    (write-line (write-to-string (fatia '(1 2 3 4 5) 0 4)))
    (write-line (write-to-string (fatia '(1 2 3 4 5) 0 5)))
    (write-line (write-to-string (fatia '(1 2 3 4 5) 4 5)))
    (write-line (write-to-string (fatia '(1 2 3 4 5) 3 5)))
    (write-line (write-to-string (fatia '(1 2 3 4 5) 2 5)))
    (write-line (write-to-string (fatia '(1 2 3 4 5) 1 5)))
)

(main)