(defun main()
    (write "x1=")
    (setq x1 (float (read)))
    (write "y1=")
    (setq y1 (float (read)))
    (write "z1=")
    (setq z1 (float (read)))
    (write "x2=")
    (setq x2 (float (read)))
    (write "y2=")
    (setq y2 (float (read)))
    (write "z2=")
    (setq z2 (float (read)))
    (write-line (write-to-string ((lambda (x1 y1 z1 x2 y2 z2) (sqrt (+ (expt (- x1 x2) 2) (expt (- y1 y2) 2) (expt (- z1 z2) 2)))) x1 y1 z1 x2 y2 z2)))
)

(main)