(defun mapear(lista f)
    (if (null lista)
        ()
        (append (list (funcall f (car lista))) (mapear (cdr lista) f) )
    )
)

(defun main()
    (setq l '(1 2 3 4 5 6 7 8 9))
    (write "Lista = ")
    (write-line (write-to-string l))
    (write-line (write-to-string (mapear l (lambda (x) (= (mod x 2) 0)))))
)

(main)